/* Glossary Page — socialnative.ai design system */
import { useState, useMemo } from "react";
import { Link } from "wouter";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useDemoModal } from "../App";

const TERMS = [
  { term: "Andromeda", category: "Technology", definition: "Meta's proprietary content recommendation and performance prediction engine. Andromeda powers the ranking and delivery of content across Facebook and Instagram. Social Native has exclusive access to Andromeda's predictive scoring, enabling pre-launch prediction of which creator content will perform best in Meta's paid and organic ecosystem.", related: ["1st Party Data", "Meta Partnership", "Paid Media Activation"] },
  { term: "Always-On Creator Program", category: "Strategy", definition: "A continuously running creator marketing program that generates a steady stream of fresh UGC content throughout the year, rather than relying on one-off campaign bursts. Always-on programs build a compounding content library and maintain consistent brand presence across social channels.", related: ["UGC", "Creator Marketing", "Content in Motion™"] },
  { term: "Content in Motion™", category: "Social Native", definition: "Social Native's proprietary capability that transforms existing static UGC photo libraries into shoppable short-form videos optimized for TikTok, Instagram Reels, and paid social — without additional creator shoots. Assets are scored by Meta Andromeda and TikTok AI and delivered in 9:16, 1:1, and 16:9 formats within 48 hours.", related: ["UGC", "Short-Form Video", "Andromeda"] },
  { term: "CPA (Cost Per Acquisition)", category: "Performance", definition: "The total cost to acquire one customer through a specific marketing channel or campaign. Social Native clients consistently achieve 40%+ CPA reduction versus brand-produced content by using AI-predicted high-performing creator assets in paid media.", related: ["ROAS", "Paid Media Activation", "Performance Marketing"] },
  { term: "Creator", category: "Fundamentals", definition: "An individual who produces original content for digital platforms — primarily social media — and has built an audience around their content. The term 'creator' is broader than 'influencer': it encompasses anyone who creates content professionally or semi-professionally, regardless of follower count or monetization model.", related: ["Influencer", "Micro-Influencer", "Nano-Influencer", "UGC Creator"] },
  { term: "Creator Economy", category: "Industry", definition: "The ecosystem of tools, platforms, and economic activity built around independent content creators who monetize their audiences and skills. Estimated at over $250 billion globally, the creator economy includes brand partnerships, platform monetization, merchandise, subscriptions, and digital products.", related: ["Creator", "Creator Marketing", "Influencer Marketing"] },
  { term: "Creator Marketing", category: "Fundamentals", definition: "A marketing discipline that leverages content creators — including influencers, UGC creators, and brand advocates — to produce authentic content that reaches target audiences. Creator marketing encompasses influencer partnerships, UGC programs, ambassador programs, and affiliate arrangements.", related: ["Influencer Marketing", "UGC", "Creator", "Partnership Ads"] },
  { term: "Dark Posting", category: "Paid Media", definition: "A paid social advertising technique where creator content is promoted as a sponsored post without appearing on the creator's organic feed. Dark posts allow brands to run A/B tests, target specific audience segments, and amplify creator content at scale without cluttering the creator's profile. Also known as 'whitelisting' or 'creator licensing.'", related: ["Partnership Ads", "Whitelisting", "Paid Media Activation"] },
  { term: "Earned Media Value (EMV)", category: "Performance", definition: "An estimate of the monetary value of organic social media exposure generated by creator content. Social Native focuses on downstream business outcomes (CPA, ROAS, conversions) rather than EMV alone.", related: ["CPA", "ROAS", "Performance Marketing"] },
  { term: "Engagement Rate", category: "Performance", definition: "The percentage of an audience that actively interacts with a piece of content, calculated as (likes + comments + shares + saves) divided by reach, multiplied by 100. Social Native creator content averages 21%+ engagement rate, significantly above industry benchmarks.", related: ["Creator", "UGC", "Performance Marketing"] },
  { term: "Influencer", category: "Fundamentals", definition: "A content creator who has built a substantial, engaged audience and has the ability to affect the purchasing decisions of their followers. Influencers are categorized by follower count: nano (1K–10K), micro (10K–100K), macro (100K–1M), and mega/celebrity (1M+).", related: ["Creator", "Micro-Influencer", "Nano-Influencer", "Creator Marketing"] },
  { term: "Influencer Marketing", category: "Fundamentals", definition: "A form of marketing that involves partnering with individuals who have established credibility and audiences on social media platforms to promote products or services. It is a subset of the broader creator marketing discipline.", related: ["Creator Marketing", "Influencer", "Partnership Ads", "UGC"] },
  { term: "Long-Tail Creator", category: "Strategy", definition: "A creator with a smaller but highly engaged, niche audience — typically in the micro or nano tier. Long-tail creators often deliver higher engagement rates, stronger audience trust, and better conversion performance than mega-influencers, at a fraction of the cost.", related: ["Micro-Influencer", "Nano-Influencer", "Creator", "Engagement Rate"] },
  { term: "Managed Creator Program", category: "Social Native", definition: "A fully operated creator marketing program where an external team handles all aspects of execution: discovery, outreach, contracting, content production, rights clearance, payments, and performance optimization. Contrasted with self-serve platforms where brand teams manage operations themselves.", related: ["Creator Marketing", "Always-On Creator Program", "UGC"] },
  { term: "Meta Partnership", category: "Technology", definition: "Social Native's official partnership with Meta that provides exclusive access to Meta Andromeda's predictive AI scoring and first-party data signals. This enables Social Native to predict content performance within Meta's ecosystem before campaigns launch.", related: ["Andromeda", "1st Party Data", "Partnership Ads"] },
  { term: "Micro-Influencer", category: "Fundamentals", definition: "A content creator with between 10,000 and 100,000 followers who has built a highly engaged, niche audience. Micro-influencers typically achieve higher engagement rates than macro-influencers, and their audiences perceive their recommendations as more authentic and trustworthy.", related: ["Nano-Influencer", "Influencer", "Long-Tail Creator", "Engagement Rate"] },
  { term: "Nano-Influencer", category: "Fundamentals", definition: "A content creator with between 1,000 and 10,000 followers. Nano-influencers typically have the highest engagement rates of any creator tier and are perceived as highly authentic by their audiences. They are particularly effective for hyper-local campaigns and niche product categories.", related: ["Micro-Influencer", "Influencer", "Long-Tail Creator", "UGC Creator"] },
  { term: "1st Party Data", category: "Technology", definition: "Data collected directly from a primary source — in Social Native's context, this refers to data obtained directly from Meta and TikTok's own AI systems (Andromeda and TikTok AI), as well as Social Native's proprietary dataset of 1.8M+ creator collaboration outcomes.", related: ["Andromeda", "Meta Partnership", "TikTok Partnership"] },
  { term: "Partnership Ads", category: "Paid Media", definition: "A Meta advertising format (formerly 'Branded Content Ads') that allows brands to amplify creator-produced content as paid ads, with the creator's handle visible in the ad unit. Partnership Ads consistently outperform standard brand ads in CTR and conversion because they retain the authentic feel of organic creator content.", related: ["Dark Posting", "Whitelisting", "Paid Media Activation", "Meta Partnership"] },
  { term: "Paid Media Activation", category: "Paid Media", definition: "The process of amplifying organic creator content through paid advertising spend on platforms like Meta, TikTok, YouTube, and Pinterest. Paid media activation transforms creator content from an organic reach play into a performance marketing asset.", related: ["Partnership Ads", "Dark Posting", "CPA", "ROAS"] },
  { term: "ROAS (Return on Ad Spend)", category: "Performance", definition: "A performance marketing metric that measures revenue generated for every dollar spent on advertising. ROAS equals Revenue divided by Ad Spend. Social Native optimizes creator content selection for ROAS using Meta Andromeda and TikTok AI signals.", related: ["CPA", "Paid Media Activation", "Performance Marketing"] },
  { term: "Rights Clearance", category: "Operations", definition: "The legal process of obtaining permission from a content creator to use their content for specific purposes — including paid media, e-commerce, out-of-home advertising, and other commercial applications. Rights clearance is included in every Social Native program.", related: ["UGC", "Creator", "Managed Creator Program"] },
  { term: "Short-Form Video", category: "Content", definition: "Video content typically under 60 seconds, optimized for vertical (9:16) viewing on mobile platforms including TikTok, Instagram Reels, YouTube Shorts, and Pinterest. Short-form video is the dominant content format in creator marketing, consistently outperforming static images in engagement and conversion.", related: ["Content in Motion™", "TikTok Partnership", "UGC"] },
  { term: "Spark Ads", category: "Paid Media", definition: "TikTok's native advertising format that allows brands to boost existing organic creator posts as paid ads, retaining the creator's handle, engagement counts, and native feel. Spark Ads are TikTok's equivalent of Meta's Partnership Ads.", related: ["Partnership Ads", "TikTok Partnership", "Paid Media Activation"] },
  { term: "TikTok Partnership", category: "Technology", definition: "Social Native's official partnership with TikTok that provides exclusive access to TikTok's first-party AI signals, including real-time trend data, creator performance forecasts, and native algorithm optimization insights.", related: ["1st Party Data", "Spark Ads", "Meta Partnership"] },
  { term: "UGC (User-Generated Content)", category: "Content", definition: "Original content — photos, videos, reviews, or social posts — created by real people (customers, creators, or brand advocates) rather than brand teams or professional agencies. UGC is the foundation of creator marketing and consistently outperforms brand content in paid media performance.", related: ["Creator", "UGC Creator", "Content in Motion™", "Creator Marketing"] },
  { term: "UGC Creator", category: "Content", definition: "A content creator who specializes in producing authentic, user-generated-style content for brands — often without requiring a large personal following. UGC creators are hired for content quality rather than audience reach, and their content is used primarily in paid media and e-commerce.", related: ["UGC", "Creator", "Nano-Influencer", "Paid Media Activation"] },
  { term: "Whitelisting", category: "Paid Media", definition: "A paid social advertising technique where a brand is granted permission to run ads from a creator's social media account, allowing the brand to target specific audiences with creator content that appears to come from the creator's handle. Also called 'creator licensing.'", related: ["Dark Posting", "Partnership Ads", "Spark Ads"] },
];

const CATEGORIES = ["All", ...Array.from(new Set(TERMS.map((t) => t.category))).sort()];
const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

export default function Glossary() {
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState("All");
  const { openDemo } = useDemoModal();

  const filtered = useMemo(() => {
    return TERMS.filter((t) => {
      const matchesSearch =
        !search.trim() ||
        t.term.toLowerCase().includes(search.toLowerCase()) ||
        t.definition.toLowerCase().includes(search.toLowerCase());
      const matchesCategory = activeCategory === "All" || t.category === activeCategory;
      return matchesSearch && matchesCategory;
    }).sort((a, b) => a.term.localeCompare(b.term));
  }, [search, activeCategory]);

  const groupedByLetter = useMemo(() => {
    const groups: Record<string, typeof TERMS> = {};
    filtered.forEach((t) => {
      const letter = t.term[0].toUpperCase();
      if (!groups[letter]) groups[letter] = [];
      groups[letter].push(t);
    });
    return groups;
  }, [filtered]);

  const activeLetters = Object.keys(groupedByLetter).sort();

  return (
    <>
      <Navbar />
      <main className="pt-16 bg-white min-h-screen">
        {/* Hero */}
        <section
          className="py-20 text-center"
          style={{ background: "linear-gradient(160deg, #f5f3ff 0%, #ede9fe 40%, #ffffff 100%)" }}
        >
          <div className="container max-w-3xl mx-auto">
            <div className="section-label mb-4">📖 Creator Marketing Glossary</div>
            <h1 className="text-4xl md:text-5xl font-extrabold text-[#222222] mb-4 leading-tight">
              The <span style={{ color: "#7c3aed" }}>definitive</span> glossary
            </h1>
            <p className="text-lg text-[#717171] mb-8 max-w-xl mx-auto">
              {TERMS.length} terms covering creator marketing, influencer strategy, AI-powered performance, and Social Native's proprietary technology.
            </p>
            <div className="relative max-w-lg mx-auto">
              <svg className="absolute left-4 top-1/2 -translate-y-1/2 text-[#717171]" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="11" cy="11" r="8" /><path d="m21 21-4.35-4.35" />
              </svg>
              <input
                type="text"
                placeholder="Search terms..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full pl-12 pr-4 py-3.5 rounded-xl border border-gray-200 bg-white text-[#222222] placeholder-[#717171] focus:outline-none focus:ring-2 focus:ring-[#7c3aed]/30 focus:border-[#7c3aed] text-sm shadow-sm"
              />
            </div>
          </div>
        </section>

        {/* Category filters */}
        <div className="border-b border-gray-100 bg-white sticky top-16 z-10">
          <div className="container max-w-6xl mx-auto py-3 flex gap-2 overflow-x-auto">
            {CATEGORIES.map((cat) => (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className={`flex-shrink-0 px-4 py-1.5 rounded-full text-sm font-medium transition-all ${
                  activeCategory === cat ? "text-white" : "bg-gray-100 text-[#484848] hover:bg-gray-200"
                }`}
                style={activeCategory === cat ? { background: "linear-gradient(135deg, #3b82f6, #7c3aed)" } : {}}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* Alphabet jump */}
        <div className="container max-w-6xl mx-auto py-4">
          <div className="flex flex-wrap gap-1">
            {ALPHABET.map((letter) => (
              <a
                key={letter}
                href={activeLetters.includes(letter) ? `#letter-${letter}` : undefined}
                className={`w-7 h-7 flex items-center justify-center rounded text-xs font-semibold transition-all ${
                  activeLetters.includes(letter)
                    ? "text-[#7c3aed] hover:bg-[#f5f3ff] cursor-pointer"
                    : "text-gray-300 cursor-default"
                }`}
              >
                {letter}
              </a>
            ))}
          </div>
        </div>

        {/* Terms grid */}
        <section className="pb-20">
          <div className="container max-w-6xl mx-auto">
            {filtered.length === 0 ? (
              <div className="text-center py-16">
                <div className="text-5xl mb-4">🔍</div>
                <p className="text-[#222222] font-semibold mb-2">No terms found</p>
                <p className="text-[#717171] text-sm">Try a different search or category.</p>
              </div>
            ) : (
              activeLetters.map((letter) => (
                <div key={letter} id={`letter-${letter}`} className="mb-10">
                  <div className="text-2xl font-extrabold mb-4 pb-2 border-b-2" style={{ color: "#7c3aed", borderColor: "rgba(124,58,237,0.2)" }}>
                    {letter}
                  </div>
                  <div className="grid md:grid-cols-2 gap-4">
                    {groupedByLetter[letter].map((term) => (
                      <div key={term.term} className="bg-white rounded-xl border border-gray-200 p-5 hover:border-[#7c3aed]/30 hover:shadow-sm transition-all">
                        <div className="flex items-start justify-between gap-3 mb-2">
                          <h3 className="font-bold text-[#222222] text-base leading-tight">{term.term}</h3>
                          <span className="flex-shrink-0 text-xs font-medium px-2 py-0.5 rounded-full" style={{ background: "rgba(124,58,237,0.08)", color: "#7c3aed" }}>
                            {term.category}
                          </span>
                        </div>
                        <p className="text-sm text-[#484848] leading-relaxed mb-3">{term.definition}</p>
                        {term.related.length > 0 && (
                          <div className="flex flex-wrap gap-1.5">
                            {term.related.map((r) => (
                              <span key={r} className="text-xs px-2 py-0.5 rounded-full bg-gray-100 text-[#717171]">{r}</span>
                            ))}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              ))
            )}
          </div>
        </section>

        {/* CTA */}
        <section className="py-16 bg-[#f7f7f7]">
          <div className="container max-w-2xl mx-auto text-center">
            <div className="text-3xl mb-4">🚀</div>
            <h2 className="text-2xl font-bold text-[#222222] mb-3">Ready to put these terms into practice?</h2>
            <p className="text-[#717171] mb-6">Social Native runs fully managed creator programs powered by 1st party AI data from Meta and TikTok.</p>
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <button onClick={openDemo} className="btn-gradient">
                Request a Demo
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                  <path d="M2.5 7h9M8 4l3.5 3L8 10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </button>
              <Link href="/faq" onClick={() => window.scrollTo({ top: 0, behavior: "instant" })} className="btn-outline-dark">
                Browse FAQ
              </Link>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
